version: '3.8'

services:
  app:
    build: .
    container_name: mc_crud_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mc_crud_test
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: mc_crud_db
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mc_crud_test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
